### ISSUE TITLE
Support for OBS-Portable-Ubuntu

### ISSUE THREAD

**Issue by Yorisoft** [guihkx/obs-studio#1]
First off, Thanks for the great work putting this together! I for one will be using this as my primary

I was wondering if it was at all possible to use this version of OBS ( that enables encoding on keplers GPUs ) with the [OBS Studio Portable for Ubuntu](https://github.com/wimpysworld/obs-studio-portable)??

This version comes with 50 plugins already prepackaged. Ive been using it as an alternative and would love to stick to something similar.

**Comment by guihkx** [comment]
Hi, thanks for your interest on this!

Unfortunately, the project you linked is a lot more complex than mine...

And to further complicate things, I believe that I'd have to create a separate Flatpak package for each plugin.

Check out the current list of OBS plugins already on Flathub:

```
$ flatpak search com.obsproject.Studio.Plugin
Name                     Description                                                                                    Application ID                                 Version Branch Remotes
Waveform                 Audio spectral analysis plugin for OBS                                                         com.obsproject.Studio.Plugin.waveform                  stable flathub
WebSocket Server (Legac… Remote-control OBS Studio through WebSockets, using the legacy 4.x protocol                    com.obsproject.Studio.Plugin.WebSocket                 stable flathub
Vertical Canvas          Add a vertical canvas to stream and record in secondary resolution, by Aitum                   com.obsproject.Studio.Plugin.VerticalCanvas    1.3.1   stable flathub
Transition Table         Fine-tune your transitions with a transition table                                             com.obsproject.Studio.Plugin.TransitionTable   0.2.7   stable flathub
Advanced Scene Switcher  An advanced automated scene switcher for OBS Studio                                            com.obsproject.Studio.Plugin.SceneSwitcher     1.24.2  stable flathub
Scale To Sound           Scale sources according to the sound of an audio source                                        com.obsproject.Studio.Plugin.ScaleToSound      1.2.2   stable flathub
RewardsTheater           An OBS plugin that lets your viewers redeem videos or sounds on stream via Twitch Channel Poi… com.obsproject.Studio.Plugin.RewardsTheater    1.0.5   stable flathub
OBS VkCapture            Capture Vulkan and OpenGL applications                                                         com.obsproject.Studio.Plugin.OBSVkCapture      1.4.8   stable flathub
LiveSplit One            Add LiveSplit One as a source                                                                  com.obsproject.Studio.Plugin.OBSLivesplitOne   0.3.4   stable flathub
obs-ndi                  NewTek NDI integration for OBS Studio                                                          com.obsproject.Studio.Plugin.NDI               4.13.0  stable flathub
Move Transition Plugin   Moves source to a new position during scene transition                                         com.obsproject.Studio.Plugin.MoveTransition    2.9.8   stable flathub
Input Overlay            Show keyboard, gamepad and mouse input on stream                                               com.obsproject.Studio.Plugin.InputOverlay              stable flathub
GStreamer                Encode streams and recordings using GStreamer                                                  com.obsproject.Studio.Plugin.Gstreamer         0.4.0   stable flathub
GStreamer VA-API         GStreamer-based VA-API encoder                                                                 com.obsproject.Studio.Plugin.GStreamerVaapi    0.4.1   stable flathub
DroidCam                 Use your phone as a camera source with the DroidCam app                                        com.obsproject.Studio.Plugin.DroidCam          2.3.1   stable flathub
Background Removal       Remove the background from your camera video
```

That's only 16 plugins in total, lol.

I'm not saying it's impossible to do it, but since I don't use any plugins, I don't have any motivation to try to package them, sorry.

However, I don't see why it wouldn't be possible to use most of these plugins with Flatpak.

Instead of installing them to `~/.config/obs-studio/plugins`, with Flatpak you'd install them to `~/.var/app/com.obsproject.Studio/config/obs-studio/plugins` instead.

Ideally though, I think you should politely ask the owners of these plugins if they could publish them on Flathub, because besides Flatpak being a packaging format officially supported by OBS developers, installing these plugins directly from Flathub would be much easier for users.

**Comment by Yorisoft** [comment]
Okay fair enough, that makes sense! 

One last thing, I tried installing a plugin through flatpak but it didnt install to obs :/ 

I tried installing these two:
[Async Audio Filter](https://github.com/norihiro/obs-async-audio-filter) plugin; filter that aims to fix audio glitches caused by asynchronous audio.
[Audio Pan](https://github.com/norihiro/obs-audio-pan-filter) plugin; controls stereo pan of audio sources.

After resolving missing dependencies, the command runs but it doesnt appear on obs.

**Comment by guihkx** [comment]
Hmm, I actually tried installing a random plugin from Flathub and it didn't show up on OBS either.

But I already have a suspicion of what's causing this, and it should be very easy to fix, but it will require a new release... 

> [Async Audio Filter](https://github.com/norihiro/obs-async-audio-filter) plugin; filter that aims to fix audio glitches caused by asynchronous audio.
> [Audio Pan](https://github.com/norihiro/obs-audio-pan-filter) plugin; controls stereo pan of audio sources.


Both plugins worked just fine for me, but I had to extract the .deb package they provide (for OBS 28), and then I createed the correct directory structure manually.

For Async Audio Filter:

```
$ tree -v ~/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-async-audio-filter
/home/gui/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-async-audio-filter/
├── bin
│   └── 64bit
│       └── obs-async-audio-filter.so
└── data
    └── locale
        └── en-US.ini

5 directories, 2 files
```

And for Audio Pan:

```
$ tree -v ~/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-audio-pan-filter
/home/gui/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-audio-pan-filter
├── bin
│   └── 64bit
│       └── obs-audio-pan-filter.so
└── data
    └── locale
        └── en-US.ini

5 directories, 2 files
```

**Comment by guihkx** [comment]
Just published [a new release](https://github.com/guihkx/flatpak-app-obs-studio-nvidia-legacy/releases/tag/30.0.2-sdk-11.1-flatpak-2), plugins from Flathub should work now.

I think all questions have been answered, so I'll close this.

But feel free to re-open otherwise.
